FROM kmade/harbor-node:latest

MAINTAINER Dragosh <oancea.dragosh@gmail.com>
LABEL vendor="I{ustomMade"
RUN npm i -g elm --loglevel error \
    elm-live \
    elm-upgrade \
    elm-format@exp \
    elm-test

