FROM node:7-slim AS base

MAINTAINER Dragosh <oancea.dragosh@gmail.com>
LABEL vendor="I{ustomMade"

#RUN apk add --no-cache --update \
  #dpkg-dev \
  #bash \
  #wget \
  #python \
  #python-dev \
  #py-pip \
  #build-base \
  #tini \
  #git \
  #openssh \
  #&& pip install virtualenv \
  #&& rm -rf /var/lib/apt/lists/* \
  #&& rm -rf /var/cache/apk/*

#USER root
#ENV NPM_CONFIG_PREFIX /home/node
#RUN npm config set prefix $NPM_CONFIG_PREFIX
#RUN yarn config set g $NPM_CONFIG_PREFIX
#RUN yarn config set prefix $NPM_CONFIG_PREFIX
#RUN mkdir -p $NPM_CONFIG_PREFIX
#ENV PATH=$NPM_CONFIG_PREFIX/bin:$PATH


